{
    "range": {
        "start": 0,
        "end": 48,
        "absolute_end": 48
    },
    "content": "    1.889 INFO     Updating inventory 2: aws-wcs\n    2.307 INFO     Reading Ansible inventory source: /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/ec2.py\n    2.309 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible\n    2.309 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/opt/rh/rh-python36/root/usr/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/opt/rh/rh-python36/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin\n    2.309 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python2.7/site-packages:\nTraceback (most recent call last):\n  File \"/usr/bin/awx-manage\", line 11, in <module>\n    load_entry_point('awx==3.5.0', 'console_scripts', 'awx-manage')()\n  File \"/__init__.py\", line 140, in manage\n  File \"/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line\n    utility.execute()\n  File \"/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py\", line 356, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py\", line 283, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File \"/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py\", line 330, in execute\n    output = self.handle(*args, **options)\n  File \"/inventory_import.py\", line 1148, in handle\n  File \"/inventory_import.py\", line 1038, in handle\n  File \"/inventory_import.py\", line 214, in load\n  File \"/inventory_import.py\", line 197, in command_to_json\nRuntimeError: ansible-inventory failed (rc=1) with stdout:\n\nstderr:\n\u001b[0;34mansible-inventory 2.8.0\u001b[0m\n\u001b[0;34m  config file = /etc/ansible/ansible.cfg\u001b[0m\n\u001b[0;34m  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']\u001b[0m\n\u001b[0;34m  ansible python module location = /usr/lib/python2.7/site-packages/ansible\u001b[0m\n\u001b[0;34m  executable location = /usr/bin/ansible-inventory\u001b[0m\n\u001b[0;34m  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]\u001b[0m\n\u001b[0;34mUsing /etc/ansible/ansible.cfg as config file\u001b[0m\n\u001b[1;35m [WARNING]:  * Failed to parse /var/lib/awx/venv/awx/lib64/python3.6/site-\u001b[0m\n\u001b[1;35mpackages/awx/plugins/inventory/ec2.py with script plugin: Inventory script\u001b[0m\n\u001b[1;35m(/var/lib/awx/venv/awx/lib64/python3.6/site-\u001b[0m\n\u001b[1;35mpackages/awx/plugins/inventory/ec2.py) had an execution error: ERROR: \"Error\u001b[0m\n\u001b[1;35mconnecting to AWS backend. The security token included in the request is\u001b[0m\n\u001b[1;35minvalid.\", while: getting EC2 instances\u001b[0m\n\u001b[1;35m\u001b[0m\n\u001b[0;34m  File \"/usr/lib/python2.7/site-packages/ansible/inventory/manager.py\", line 267, in parse_source\u001b[0m\n\u001b[0;34m    plugin.parse(self._inventory, self._loader, source, cache=cache)\u001b[0m\n\u001b[0;34m  File \"/usr/lib/python2.7/site-packages/ansible/plugins/inventory/script.py\", line 161, in parse\u001b[0m\n\u001b[0;34m    raise AnsibleParserError(to_native(e))\u001b[0m\n\u001b[0;34m\u001b[0m\n\u001b[1;35m [WARNING]: Unable to parse /var/lib/awx/venv/awx/lib64/python3.6/site-\u001b[0m\n\u001b[1;35mpackages/awx/plugins/inventory/ec2.py as an inventory source\u001b[0m\n\u001b[1;35m\u001b[0m\n\u001b[0;31mERROR! No inventory was parsed, please check your configuration and options.\u001b[0m\n\n"
}